#!/bin/bash


# Author hys
rd=/d/dev
dd="${rd}/dev"

# stdin check
if [ -p !/dev/stdin ]; then
	echo "no stdin"
	exit
fi
pd=$( </dev/stdin )
if [[ -e !"${rd}/${pd}" ]]; then
	echo "invalid project directory"
	exit
fi

# module directory check & mkdir
md="${rd}/${pd}/module" 
if [[ -e $md ]]; then
	echo "${md} is already exist"
	read -p "${md} update ok? (y/n):" yn </dev/tty
	if [[ $yn != y ]]; then
		exit
	fi
else
	mkdir ${md} 
fi
for f in $(find . -maxdepth 1 -type f); do
	if [[ ${f:2} != "./.gitignore" ]]; then
		cat $f > "${md}/${f:2}"
	fi
done

# revision directory check & mkdir
yyyymmdd=$(date "+%Y%m%d")
if [[ -e $yyyymmdd ]]; then
	echo "${yyyymmdd} is already exist"
	read -p "${yyyymmdd} update ok? (y/n):" yn </dev/tty
	if [[ $yn != y ]]; then
		exit
	fi
else
	mkdir $yyyymmdd 
fi
for f in $(find . -maxdepth 1 -type f); do
	if [[ $f != "./.gitignore" ]]; then
		cat $f > "${yyyymmdd}/${f}"
	fi
done

git add .;
git status;
read -p "commit ok? (y/n):" yn </dev/tty

case $yn in
	y) 
		git add .;
		git commit -m"${yyyymmdd}.${yyyymmdd}.${yyyymmdd}";
		;;
	*) 
esac
