#!/bin/bash


# Author hys
git add .;
git status;
read -p "commit ok? (y/n):" yn
case $yn in
	y) 
		yyyymmdd=$(date "+%Y%m%d")
		mkdir $yyyymmdd
		for f in $(find . -maxdepth 1 -type f); do
			if [[ $f != "./.gitignore" ]]; then
				cat $f > "${yyyymmdd}/${f}"
			fi
		done
		git add .;
		git commit -m"${yyyymmdd}.${yyyymmdd}.${yyyymmdd}";
		;;
	*) 
esac
